### ISSUE TITLE
SDK 3.0.1

### ISSUE THREAD

**Issue by luckybulldozer** [DJI-Mobile-SDK-Tutorials/iOS-GSDemo#1] opened 2016-02-15 08:58 UTC
Just wondering if/when this will be updated to the latest SDK?  Working out the new methods is not that fun!

**Comment by dji-dev** [comment] 2016-02-17 07:35
Hi, we will update this tutorial to SDK 3.0.1 soon. Thanks!

**Comment by dji-dev** [comment] 2016-07-25 16:16
Hi, the GSDemo is already updated to SDK 3.2, please check it. Since the issue is solved, I will close it.

**Closed as completed by dji-dev** 2016-07-25 16:16 UTC
